export const CREATE_ANIMAL_ADOPTION_REQUEST = 'CREATE_ANIMAL_ADOPTION_REQUEST';
export const CREATE_ANIMAL_ADOPTION_REQUEST_SUCCESS = 'CREATE_ANIMAL_ADOPTION_REQUEST_SUCCESS';
export const CREATE_ANIMAL_ADOPTION_REQUEST_FAILURE = 'CREATE_ANIMAL_ADOPTION_REQUEST_FAILURE';

export const createAnimalAdoptionRequest = () => ({
  type: CREATE_ANIMAL_ADOPTION_REQUEST,

})
